<ul id="menu" class="page-sidebar-menu">
    <!-- DASHBOARD -->
    <li {!! (Request::is('dashboard') ? 'class="active"' : '') !!}>
        <a href="#">
            <i class="livicon" data-name="home" data-size="18" data-c="#418BCA" data-hc="#418BCA"
               data-loop="true"></i>
            <span class="title">Dashboard</span>
        </a>
    </li>

    <!-- FIND INVESTMENT -->
    <li {!! (Request::is('groups') || Request::is('groups/create') || Request::is('groups/*') ? 'class="active"' : '') !!}>
        <a href="#">
            <i class="livicon" data-name="rocket" data-size="18" data-c="#418BCA" data-hc="#418BCA"
               data-loop="true"></i>
            <span class="title">Investments</span>
            <span class="fa arrow"></span>
        </a>
        <ul class="sub-menu">
            <li {!! (Request::is('groups') ? 'class="active" id="active"' : '') !!}>
                <a href="#">
                    <i class="fa fa-angle-double-right"></i>
                    All Investments
                </a>
            </li>
        </ul>
        <ul class="sub-menu">
            <li {!! (Request::is('groups') ? 'class="active" id="active"' : '') !!}>
                <a href="/investment-admin/create">
                    <i class="fa fa-angle-double-right"></i>
                    New Investments
                </a>
            </li>
        </ul>
    </li>

    <!-- Menus generated by CRUD generator -->
    @include('investment-admin.layouts.menu')
</ul>
